apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
data:
  mongo-init.js: |
    printjson(rs.initiate())
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo  
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        args: ['--replSet', 'rs0', '--oplogSize', '128']
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-init
          mountPath: /docker-entrypoint-initdb.d/mongo-init.js
          subPath: mongo-init.js
      volumes: 
      - name: mongo-init
        configMap:
          name: mongo-init
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
    - port: 27017
  selector:
    app: mongo
  clusterIP: None
